name: Build VoidLink IPA

permissions:
  contents: write

on:
  push:
    branches:
      - Integration

jobs:
  build:
    name: Build VoidLink IPA
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout submodules
        run: "git submodule update --init --recursive"

      - name: Build VoidLink
        run: |
          xcodebuild -verbose -scheme VoidLink -sdk iphoneos -configuration Debug archive -archivePath $PWD/build/VoidLink.xcarchive CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED="NO" CODE_SIGN_ENTITLEMENTS="" CODE_SIGNING_ALLOWED="NO"
          mkdir -p ./build/IPA && mkdir -p ./build/IPA/Payload
          cp -r ./build/VoidLink.xcarchive/Products/Applications/VoidLink.app ./build/IPA/Payload/VoidLink.app
          cd ./build/IPA && zip -r ../../build/VoidLink.ipa ./Payload/* && cd ../..

      - name: Upload VoidLink IPA to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: VoidLink.ipa
          path: build/VoidLink.ipa

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download IPA
        uses: actions/download-artifact@v4
        with:
          name: VoidLink.ipa
          path: ./build

      - name: Generate release body
        id: get_release_body
        run: |
          body=$(echo '${{ toJSON(github.event.commits) }}' | jq -r '.[] | .message | split("\n")[0] | "- " + .')
          echo "body<<EOF" >> $GITHUB_ENV
          echo "$body" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Delete previous autobuild release
        uses: dev-drprasad/delete-tag-and-release@v0.2.1
        with:
          tag_name: autobuild
          delete_release: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: autobuild
          name: VoidLink AutoBuild - ${{ env.TODAY }}
          body: ${{ env.body }}
          files: build/VoidLink.ipa
        env:
          TODAY: $(date +'%Y%m%d')
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
